import type { MeetingType } from "@/drizzle/schema";

export type MeetingAgendaItemDTO = {
  id: string;
  agendaId: string;
  orderIndex: number;
  title: string;
  bodyMarkdown: string;
  relatedTeamId: string | null;
  relatedPilotRunId: string | null;
  relatedScenarioId: string | null;
  isAutoGenerated: boolean;
};

export type MeetingAgendaDTO = {
  id: string;
  workspaceId: string;
  reportId: string | null;
  type: MeetingType;
  title: string;
  description: string | null;
  scheduledAt: string | null;
  durationMinutes: number | null;
  createdByUserId: string;
  createdAt: string;
  updatedAt: string;
  items: MeetingAgendaItemDTO[];
};
