import type { ReportGeneratedFrom, ReportSectionKey, ReportStatus, ReportType } from "@/drizzle/schema";

export type ReportSectionDTO = {
  id: string;
  reportId: string;
  key: ReportSectionKey | string | null;
  title: string;
  orderIndex: number;
  contentMarkdown: string;
  isAutoGenerated: boolean;
};

export type ReportDTO = {
  id: string;
  workspaceId: string;
  type: ReportType;
  title: string;
  teamId: string | null;
  pilotRunId: string | null;
  generatedFrom: ReportGeneratedFrom | null;
  status: ReportStatus;
  createdByUserId: string;
  createdAt: string;
  updatedAt: string;
  sections: ReportSectionDTO[];
};
