import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getWorkspaceContextFromRequest } from "@/lib/workspaceContext";
import { updateReportSection } from "@/services/reportService";
import { requireRole } from "@/services/rbac";
import {
  authRequiredError,
  forbiddenError,
  internalError,
  notFoundError,
  respondWithApiError,
  validationError,
} from "@/services/apiError";

type RouteParams = { params: { id: string; sectionId: string } };

const schema = z.object({
  title: z.string().optional(),
  contentMarkdown: z.string().optional(),
  orderIndex: z.number().optional(),
  isAutoGenerated: z.boolean().optional(),
});

export async function PATCH(request: NextRequest, { params }: RouteParams) {
  const context = await getWorkspaceContextFromRequest(request);
  if (!context) return respondWithApiError(authRequiredError());
  try {
    await requireRole(context.workspace.id, context.user.id, ["owner", "admin"]);
  } catch {
    return respondWithApiError(forbiddenError());
  }
  const json = await request.json().catch(() => null);
  const parsed = schema.safeParse(json);
  if (!parsed.success) {
    return respondWithApiError(validationError(parsed.error.flatten().fieldErrors));
  }
  try {
    const section = await updateReportSection({
      reportId: params.id,
      sectionId: params.sectionId,
      workspaceId: context.workspace.id,
      ...parsed.data,
    });
    if (!section) {
      return respondWithApiError(notFoundError("Секция не найдена"));
    }
    return NextResponse.json({ ok: true, section });
  } catch (error) {
    return respondWithApiError(await internalError(error, { route: "reports:section:update", reportId: params.id, sectionId: params.sectionId }));
  }
}
