import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getWorkspaceContextFromRequest } from "@/lib/workspaceContext";
import { updateAgendaItem } from "@/services/meetingService";
import { requireRole } from "@/services/rbac";
import {
  authRequiredError,
  forbiddenError,
  internalError,
  notFoundError,
  respondWithApiError,
  validationError,
} from "@/services/apiError";

type RouteParams = { params: { id: string; itemId: string } };

const schema = z.object({
  title: z.string().optional(),
  bodyMarkdown: z.string().optional(),
  orderIndex: z.number().optional(),
  isAutoGenerated: z.boolean().optional(),
});

export async function PATCH(request: NextRequest, { params }: RouteParams) {
  const context = await getWorkspaceContextFromRequest(request);
  if (!context) return respondWithApiError(authRequiredError());
  try {
    await requireRole(context.workspace.id, context.user.id, ["owner", "admin"]);
  } catch {
    return respondWithApiError(forbiddenError());
  }
  const json = await request.json().catch(() => null);
  const parsed = schema.safeParse(json);
  if (!parsed.success) {
    return respondWithApiError(validationError(parsed.error.flatten().fieldErrors));
  }
  try {
    const item = await updateAgendaItem({
      agendaId: params.id,
      itemId: params.itemId,
      workspaceId: context.workspace.id,
      title: parsed.data.title,
      bodyMarkdown: parsed.data.bodyMarkdown,
      orderIndex: parsed.data.orderIndex,
      isAutoGenerated: parsed.data.isAutoGenerated,
    });
    if (!item) {
      return respondWithApiError(notFoundError("Пункт повестки не найден"));
    }
    return NextResponse.json({ ok: true, item });
  } catch (error) {
    return respondWithApiError(await internalError(error, { route: "meetings:item:update", agendaId: params.id, itemId: params.itemId }));
  }
}
