import { randomUUID } from "crypto";
import { beforeEach, describe, expect, it } from "vitest";
import { db } from "@/lib/db";
import { employees, meetingAgendaItems, meetingAgendas, pilotRunTeams, pilotRuns, talentDecisions, tracks } from "@/drizzle/schema";
import { getManagerHome } from "@/services/managerHomeService";
import { createWorkspace } from "@/repositories/workspaceRepository";
import { createMember } from "@/repositories/memberRepository";
import { createUser } from "@/repositories/userRepository";
import { ensureDefaultTestPlan } from "@/tests/utils/planTestHelper";
import { resetWorkspaceData } from "@/tests/utils/dbCleaner";

describe("managerHomeService", () => {
  let workspaceId: string;
  let userId: string;
  let teamId: string;
  let employeeId: string;

  beforeEach(async () => {
    await resetWorkspaceData({ includePlans: true });
    const plan = await ensureDefaultTestPlan();
    const user = await createUser({ email: `mgr+${randomUUID()}@example.com`, passwordHash: "hash", name: "Manager" });
    userId = user.id;
    const workspace = await createWorkspace({ name: "Manager WS", ownerUserId: userId, size: "10-50", planId: plan?.id });
    workspaceId = workspace.id;
    await createMember({ userId, workspaceId, role: "owner" });
    teamId = randomUUID();
    db.insert(tracks)
      .values({ id: teamId, workspaceId, name: "Team A", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() })
      .run();
    employeeId = randomUUID();
    db.insert(employees)
      .values({
        id: employeeId,
        workspaceId,
        name: "Manager",
        position: "Lead",
        level: "Senior",
        primaryTrackId: teamId,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      })
      .run();
    // another team member
    db.insert(employees)
      .values({
        id: randomUUID(),
        workspaceId,
        name: "Engineer",
        position: "Dev",
        level: "Middle",
        primaryTrackId: teamId,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      })
      .run();
    // pilot
    const pilotId = randomUUID();
    db.insert(pilotRuns)
      .values({
        id: pilotId,
        workspaceId,
        name: "Pilot 1",
        description: null,
        status: "active",
        ownerUserId: userId,
        targetCycleId: null,
        createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      })
      .run();
    db.insert(pilotRunTeams)
      .values({ id: randomUUID(), pilotRunId: pilotId, teamId })
      .run();
    // decision risk
    db.insert(talentDecisions)
      .values({
        id: randomUUID(),
        workspaceId,
        employeeId,
        type: "monitor_risk",
        sourceType: "manual",
        sourceId: null,
        status: "proposed",
        priority: "medium",
        title: "Risk",
        rationale: "At risk",
        risks: null,
        timeframe: null,
        createdByUserId: userId,
        createdAt: new Date(),
        updatedAt: new Date(),
      })
      .run();
    // meeting upcoming
    const agendaId = randomUUID();
    db.insert(meetingAgendas)
      .values({
        id: agendaId,
        workspaceId,
        reportId: null,
        type: "team_review",
        title: "Team sync",
        description: null,
        scheduledAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
        durationMinutes: 30,
        createdByUserId: userId,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      })
      .run();
    db.insert(meetingAgendaItems)
      .values({ id: randomUUID(), agendaId, orderIndex: 0, title: "Team", bodyMarkdown: "", relatedTeamId: teamId, relatedPilotRunId: null, relatedScenarioId: null, isAutoGenerated: true })
      .run();
  });

  it("builds summary and actions for manager", async () => {
    const result = await getManagerHome({ workspaceId, userId });
    expect(result.summary.headcount).toBe(2);
    expect(result.summary.pilotsActive).toBeGreaterThan(0);
    expect(result.summary.employeesAtRisk).toBe(1);
    expect(result.summary.openDecisions).toBe(1);
    expect(result.upcomingMeetings.length).toBeGreaterThan(0);
    const scheduleAction = result.actions.find((a) => a.kind === "schedule_one_to_one");
    expect(scheduleAction).toBeTruthy();
    const closeDecision = result.actions.find((a) => a.kind === "close_decision");
    expect(closeDecision).toBeTruthy();
  });
});
