"use client";

import { useState } from "react";
import Card from "@/components/common/Card";
import PrimaryButton from "@/components/common/PrimaryButton";
import SecondaryButton from "@/components/common/SecondaryButton";
import type { MeetingAgendaDTO } from "@/services/types/meeting";

type MeetingAgendaClientProps = {
  agenda: MeetingAgendaDTO;
  workspaceId: string;
};

export default function MeetingAgendaClient({ agenda: initialAgenda }: MeetingAgendaClientProps) {
  const [agenda, setAgenda] = useState(initialAgenda);
  const [error, setError] = useState<string | null>(null);
  const [metaSaving, setMetaSaving] = useState(false);
  const [metaForm, setMetaForm] = useState({
    title: agenda.title,
    description: agenda.description ?? "",
    scheduledAt: agenda.scheduledAt ?? "",
    durationMinutes: agenda.durationMinutes ?? undefined,
  });

  const copyAgenda = async () => {
    const text = [
      agenda.title,
      agenda.scheduledAt ? `Когда: ${new Date(agenda.scheduledAt).toLocaleString("ru-RU")}` : "",
      "",
      ...agenda.items.map((item, idx) => `${idx + 1}. ${item.title}\n${item.bodyMarkdown.split("\n").map((line) => `   - ${line}`).join("\n")}`),
    ]
      .filter(Boolean)
      .join("\n");
    await navigator.clipboard.writeText(text);
    alert("Повестка скопирована");
  };

  const copyShort = async () => {
    const text = [
      `Краткий отчёт: ${agenda.title}`,
      agenda.items
        .slice(0, 4)
        .map((item) => `- ${item.title}: ${item.bodyMarkdown.split("\n")[0] ?? ""}`)
        .join("\n"),
    ].join("\n");
    await navigator.clipboard.writeText(text);
    alert("Краткий отчёт скопирован");
  };

  const saveMeta = async () => {
    setMetaSaving(true);
    setError(null);
    try {
      const response = await fetch(`/api/app/meetings/agendas/${agenda.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: metaForm.title,
          description: metaForm.description,
          scheduledAt: metaForm.scheduledAt || null,
          durationMinutes: metaForm.durationMinutes ?? null,
        }),
      });
      const payload = await response.json().catch(() => null);
      if (!response.ok || !payload?.ok) throw new Error(payload?.error?.message ?? "Не удалось сохранить");
      setAgenda(payload.agenda);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Ошибка сохранения");
    } finally {
      setMetaSaving(false);
    }
  };

  const saveItem = async (itemId: string, data: Partial<{ title: string; bodyMarkdown: string; orderIndex: number; isAutoGenerated: boolean }>) => {
    setError(null);
    const response = await fetch(`/api/app/meetings/agendas/${agenda.id}/items/${itemId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(data),
    });
    const payload = await response.json().catch(() => null);
    if (!response.ok || !payload?.ok) {
      setError(payload?.error?.message ?? "Не удалось сохранить пункт");
      return;
    }
    setAgenda((prev) => ({
      ...prev,
      items: prev.items.map((item) => (item.id === itemId ? { ...item, ...data } : item)),
    }));
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
        <div>
          <p className="text-xs uppercase tracking-[0.4em] text-slate-400">Встреча</p>
          <h1 className="text-3xl font-semibold text-brand-text">{agenda.title}</h1>
          <p className="text-sm text-slate-600">
            {formatType(agenda.type)} · {agenda.scheduledAt ? new Date(agenda.scheduledAt).toLocaleString("ru-RU") : "Дата не назначена"}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <SecondaryButton onClick={() => void copyAgenda()} className="px-3 py-1 text-xs">
            Скопировать повестку
          </SecondaryButton>
          <SecondaryButton onClick={() => void copyShort()} className="px-3 py-1 text-xs">
            Скопировать кратко
          </SecondaryButton>
        </div>
      </div>

      {error && <Card className="border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</Card>}

      <Card className="space-y-3">
        <p className="text-xs uppercase tracking-[0.3em] text-slate-400">Мета</p>
        <div className="grid gap-3 md:grid-cols-2">
          <label className="text-sm text-slate-600">
            Название
            <input
              value={metaForm.title}
              onChange={(event) => setMetaForm((prev) => ({ ...prev, title: event.target.value }))}
              className="mt-1 w-full rounded-xl border border-brand-border px-3 py-2 text-sm"
            />
          </label>
          <label className="text-sm text-slate-600">
            Дата/время
            <input
              value={metaForm.scheduledAt}
              onChange={(event) => setMetaForm((prev) => ({ ...prev, scheduledAt: event.target.value }))}
              className="mt-1 w-full rounded-xl border border-brand-border px-3 py-2 text-sm"
              placeholder="2025-01-01T10:00"
            />
          </label>
        </div>
        <label className="text-sm text-slate-600">
          Описание
          <textarea
            value={metaForm.description}
            onChange={(event) => setMetaForm((prev) => ({ ...prev, description: event.target.value }))}
            className="mt-1 w-full rounded-xl border border-brand-border px-3 py-2 text-sm"
            rows={3}
          />
        </label>
        <label className="text-sm text-slate-600">
          Длительность (мин)
          <input
            type="number"
            value={metaForm.durationMinutes ?? ""}
            onChange={(event) => setMetaForm((prev) => ({ ...prev, durationMinutes: Number(event.target.value) || undefined }))}
            className="mt-1 w-full rounded-xl border border-brand-border px-3 py-2 text-sm"
          />
        </label>
        <PrimaryButton onClick={() => void saveMeta()} disabled={metaSaving} className="px-4 py-2">
          Сохранить мета
        </PrimaryButton>
      </Card>

      <Card className="space-y-3">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.3em] text-slate-400">Повестка</p>
            <h2 className="text-xl font-semibold text-brand-text">Пункты</h2>
          </div>
        </div>
        <div className="space-y-3">
          {agenda.items.map((item, index) => (
            <div key={item.id} className="rounded-2xl border border-white/60 bg-white/90 p-3">
              <div className="flex items-center justify-between gap-3">
                <input
                  value={item.title}
                  onChange={(event) =>
                    setAgenda((prev) => ({
                      ...prev,
                      items: prev.items.map((i) => (i.id === item.id ? { ...i, title: event.target.value } : i)),
                    }))
                  }
                  className="w-full rounded-xl border border-brand-border px-3 py-2 text-sm"
                />
                <div className="flex gap-1">
                  <SecondaryButton onClick={() => moveItem(index, -1)} disabled={index === 0} className="px-3 py-1 text-xs">
                    ↑
                  </SecondaryButton>
                  <SecondaryButton
                    onClick={() => moveItem(index, 1)}
                    disabled={index === agenda.items.length - 1}
                    className="px-3 py-1 text-xs"
                  >
                    ↓
                  </SecondaryButton>
                </div>
              </div>
              <textarea
                value={item.bodyMarkdown}
                onChange={(event) =>
                  setAgenda((prev) => ({
                    ...prev,
                    items: prev.items.map((i) => (i.id === item.id ? { ...i, bodyMarkdown: event.target.value } : i)),
                  }))
                }
                className="mt-2 w-full rounded-xl border border-brand-border px-3 py-2 text-sm font-mono"
                rows={4}
              />
              <div className="mt-2 flex items-center justify-between">
                <label className="flex items-center gap-2 text-sm text-slate-600">
                  <input
                    type="checkbox"
                    checked={item.isAutoGenerated}
                    onChange={(event) =>
                      setAgenda((prev) => ({
                        ...prev,
                        items: prev.items.map((i) => (i.id === item.id ? { ...i, isAutoGenerated: event.target.checked } : i)),
                      }))
                    }
                  />
                  Автогенерация
                </label>
                <PrimaryButton
                  onClick={() =>
                    void saveItem(item.id, {
                      title: item.title,
                      bodyMarkdown: item.bodyMarkdown,
                      orderIndex: item.orderIndex,
                      isAutoGenerated: item.isAutoGenerated,
                    })
                  }
                  className="px-3 py-1 text-xs"
                >
                  Сохранить пункт
                </PrimaryButton>
              </div>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );

  function moveItem(index: number, delta: number) {
    setAgenda((prev) => {
      const copy = [...prev.items];
      const target = index + delta;
      if (target < 0 || target >= copy.length) return prev;
      const [removed] = copy.splice(index, 1);
      copy.splice(target, 0, removed);
      return { ...prev, items: copy.map((item, idx) => ({ ...item, orderIndex: idx })) };
    });
  }
}

function formatType(type: string) {
  const map: Record<string, string> = {
    team_review: "Командная встреча",
    pilot_review: "Обзор пилота",
    exec_briefing: "Executive briefing",
  };
  return map[type] ?? type;
}
